ASSIGNMENT 6


In [1]:
import numpy as np

Q1. Consider the following sensor readings:                           temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40]) A sensor has an average measurement error of +2°C. Perform the following without using a for loop:                                                     
 a. Add 2°C to every reading using vectorization.    
 b. Convert all temperatures from Celsius to Fahrenheit using: F =9 /5 C +32                     
 c. Identify all readings greater than 32°C using Boolean indexing.  
 d. Count how many readings exceed
 32°

 e. Explain how vectorization and Boolean indexing can make data processing more efficient than explicitly iterating through every value.                                                           

In [4]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

corrected = temperature + 2
print("Corrected temperatures:", corrected)

fahrenheit = (9/5) * corrected + 32
print("Fahrenheit:", fahrenheit)

greater_than_32 = corrected[corrected > 32]
print("Readings greater than 32°C:", greater_than_32)

count = np.sum(corrected > 32)
print("Count:", count)

print("e. Vectorization allows NumPy to perform operations on the entire array")
print("   at once without using a for loop, making the code faster and shorter.")
print("   Boolean indexing selects only the values that satisfy a condition,")
print("   making data processing more efficient, especially for large datasets.")

Corrected temperatures: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Count: 5
e. Vectorization allows NumPy to perform operations on the entire array
   at once without using a for loop, making the code faster and shorter.
   Boolean indexing selects only the values that satisfy a condition,
   making data processing more efficient, especially for large datasets.


Q2. The following matrix represents the number of daily steps recorded by four users over three days: steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]]) Perform the following:

a. Calculate the total steps recorded.                                              
b. Calculate the mean number of steps.                                            
c. Find the maximum and minimum values.                                          
d. Calculate the total steps for each day using axis=0.                            
e. Calculate the total steps for each user using axis=1.                         
f. Find the user/day position containing the maximum number of steps using argmax().

In [5]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

total = np.sum(steps)
print("a. Total steps:", total)


mean = np.mean(steps)
print("b. Mean steps:", mean)

maximum = np.max(steps)
minimum = np.min(steps)
print("c. Maximum steps:", maximum)
print("   Minimum steps:", minimum)

day_total = np.sum(steps, axis=0)
print("d. Total steps for each day:", day_total)

user_total = np.sum(steps, axis=1)
print("e. Total steps for each user:", user_total)

position = np.unravel_index(np.argmax(steps), steps.shape)
print("f. Position of maximum steps:", position)
print("   Maximum steps:", steps[position])

a. Total steps: 84200
b. Mean steps: 7016.666666666667
c. Maximum steps: 9500
   Minimum steps: 4500
d. Total steps for each day: [26500 27300 30400]
e. Total steps for each user: [18300 24500 14400 27000]
f. Position of maximum steps: (np.int64(3), np.int64(2))
   Maximum steps: 9500


Q3. Write a Python program using NumPy to perform the following operations:      
a. Create the following NumPy array: original = np.array([1, 2, 3, 4, 5, 6])     
b. Create a slice containing elements from index 1 to 4 and store it in a variable named subset.                                                           
c. Modify the first element of subset to 999 and display both original and subset.  
d. Create another slice from original, but this time use .copy(). Modify its first element to 500 and display original and the copied array.                                                                          e. Create a NumPy array containing the numbers from 1 to 12 using np.arange() and reshape it into a 3 × 4 matrix.

f. From the 3 × 4 matrix, extract the following using NumPy indexing and slicing: • First row  • Last row  • Second column  • Elements from rows 1–2 and columns 2–3                                                                      
g. Create a flattened version of the 3 × 4 matrix using both flatten() and ravel().                                                                              
h. Modify an element in the array returned by ravel() and observe whether the original array is affected.                                                      
i. Modify an element in the array returned by flatten() and observe whether the original array is affected.                                                          
j. Display the shape, ndim, size, and dtype of the original 3 × 4 matrix.


In [6]:

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a. Calculate total steps
total = np.sum(steps)
print("a. Total steps:", total)

# b. Calculate mean
mean = np.mean(steps)
print("b. Mean steps:", mean)

# c. Maximum and minimum
maximum = np.max(steps)
minimum = np.min(steps)
print("c. Maximum steps:", maximum)
print("   Minimum steps:", minimum)

# d. Total steps for each day (axis=0)
day_total = np.sum(steps, axis=0)
print("d. Total steps for each day:", day_total)

# e. Total steps for each user (axis=1)
user_total = np.sum(steps, axis=1)
print("e. Total steps for each user:", user_total)

# f. Position of maximum number of steps
position = np.unravel_index(np.argmax(steps), steps.shape)
print("f. Position of maximum steps:", position)
print("   Maximum steps:", steps[position])

a. Total steps: 84200
b. Mean steps: 7016.666666666667
c. Maximum steps: 9500
   Minimum steps: 4500
d. Total steps for each day: [26500 27300 30400]
e. Total steps for each user: [18300 24500 14400 27000]
f. Position of maximum steps: (np.int64(3), np.int64(2))
   Maximum steps: 9500


Q4. A simple cognitive-assistive system wants to predict a user's assistance score based on three factors: • Sleep hours  • Activity level  • Stress level    
Consider: y = np.array([40, 65, 30, 85]) X = np.array([ [6, 70, 3], [5, 50, 6], [8, 80, 2], [4, 30, 8] ]) Here, each row represents one user and each column represents a feature. Perform the following:                                           
a. Display the shape and dimensions of X.                                        
b. Calculate: X.T and explain what the transpose represents.                      
c. Calculate the matrix product: X.T @ X                                         
d. Calculate the matrix inverse using: np.linalg.inv() where appropriate.        
e. Implement the Ordinary Least Squares equation: 𝛽 = (𝑋𝑋) 𝑋𝑦 using NumPy.  
f. Explain what the resulting coefficients represent in the context of the three user features.                                                             
g. A new user has: new_user = np.array([5, 40, 7]) Use your calculated coefficients to obtain a predicted assistance score.                              

In [7]:
import numpy as np

# Given data
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])


# a. Display shape and dimensions of X
print("a. Shape of X:", X.shape)
print("   Dimensions of X:", X.ndim)


# b. Calculate X.T
print("\nb. Transpose of X:")
print(X.T)

print("   Transpose changes rows into columns and columns into rows.")


# c. Calculate X.T @ X
XT_X = X.T @ X

print("\nc. X.T @ X:")
print(XT_X)


# d. Calculate matrix inverse
inverse = np.linalg.inv(XT_X)

print("\nd. Inverse of X.T @ X:")
print(inverse)


# e. Ordinary Least Squares equation
# Beta = (X.T X)^-1 X.T y

beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("\ne. OLS Coefficients (Beta):")
print(beta)


# f. Explain the coefficients
print("\nf. Meaning of coefficients:")
print("   Sleep hours coefficient:", beta[0])
print("   Activity level coefficient:", beta[1])
print("   Stress level coefficient:", beta[2])
print("   These coefficients represent the estimated effect of each")
print("   feature on the assistance score when the other features")
print("   are kept constant.")


# g. Predict assistance score for new user
new_user = np.array([5, 40, 7])

prediction = new_user @ beta

print("\ng. New user:", new_user)
print("   Predicted assistance score:", prediction)

a. Shape of X: (4, 3)
   Dimensions of X: 2

b. Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
   Transpose changes rows into columns and columns into rows.

c. X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

d. Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e. OLS Coefficients (Beta):
[-0.15921454  0.14083853 10.06302242]

f. Meaning of coefficients:
   Sleep hours coefficient: -0.1592145415946895
   Activity level coefficient: 0.14083852991906243
   Stress level coefficient: 10.063022422714587
   These coefficients represent the estimated effect of each
   feature on the assistance score when the other features
   are kept constant.

g. New user: [ 5 40  7]
   Predicted assistance score: 75.27862544779117
