ASSIGNMENT 5


In [2]:
import numpy as np

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:                                                            
 a) Addition of 2 in all the element                                                                                                                                                     b) Multiply 3 with all the elements c) Divide every element by 2

In [3]:
arr =np.array([10,20,30,40,50])
print(arr+2)
print(arr * 3)
print(arr/2)

[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array:                                              
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])                             
b) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [4]:
arr = np.array([1,2,3,6,4,5])
print("Original array",arr)
print("Reversed array",arr[::-1])

Original array [1 2 3 6 4 5]
Reversed array [5 4 6 3 2 1]


In [5]:
x= np.array([1,2,3,4,5,1,2,1,1,1])
values,counts=np.unique(x,return_counts=True)
max_count = counts.max()
most_frequent=values[counts==max_count]
print("Most frequent value",most_frequent)
print("Indices:",np.where(np.isin(x,most_frequent))[0])

Most frequent value [1]
Indices: [0 5 7 8 9]


In [6]:
y= np.array([1,1,1,2,3,4,2,4,3,3])
values,counts=np.unique(x,return_counts=True)
max_count = counts.max()
most_frequent=values[counts==max_count]
print("Most frequent value",most_frequent)
print("Indices:",np.where(np.isin(x,most_frequent))[0])

Most frequent value [1]
Indices: [0 5 7 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:                                                                                  a) Access 1st row, 2nd column                                                                        b) Access 3rd row, 1st column

In [8]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0,1])
print(arr[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?


In [10]:
Shruti = np.linspace(10,100,25)
print("Array")
print(Shruti)
print("Dimensions:",Shruti.ndim)
print("Shape",Shruti.shape)
print("Total elements",Shruti.size)
print("Data Type",Shruti.dtype)
print("Total Bytes",Shruti.nbytes)

transpose_Shruti=Shruti.reshape(25,1)

print("Transpose using reshape()")
print(transpose_Shruti)

print("Transpose using T")
print(Shruti.T)


Array
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape (25,)
Total elements 25
Data Type float64
Total Bytes 200
Transpose using reshape()
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [13]:
ucs420_Shruti = np.array([
    [10,20,30,40],
    [50,60,70,80],
    [90,15,20,35]
])

print("Original Array")
print(ucs420_Shruti)

print("Mean",np.mean(ucs420_Shruti))
print("Median",np.median(ucs420_Shruti))
print("Max",np.max(ucs420_Shruti))
print("Min",np.min(ucs420_Shruti))
print("Unique elements",np.unique(ucs420_Shruti))

reshaped_ucs420_Shruti = ucs420_Shruti.reshape(4,3)
print("Reshaped array:")
print(reshaped_ucs420_Shruti)

resized_ucs420_Shruti=np.resize(ucs420_Shruti,(2,3))
print("Resized array")
print(resized_ucs420_Shruti)

Original Array
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean 43.333333333333336
Median 37.5
Max 90
Min 10
Unique elements [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array
[[10 20 30]
 [40 50 60]]
